# Generated by Django 6.0 on 2025-12-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hieroglyph', models.CharField(max_length=255)),
                ('translate', models.CharField(max_length=255)),
                ('transcription', models.CharField(max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
    ]
