# Generated by Django 6.0 on 2025-12-10 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Изучена')),
                ('times_viewed', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('times_correct', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('times_incorrect', models.IntegerField(default=0, verbose_name='Неправильных ответов')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='Последний просмотр')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Личные заметки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to='trainer.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Карточка в словаре',
                'verbose_name_plural': 'Карточки в словаре',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='MyDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('cards', models.ManyToManyField(related_name='in_dictionaries', through='trainer.DictionaryCard', to='trainer.card', verbose_name='Карточки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мой словарь',
                'verbose_name_plural': 'Мои словари',
            },
        ),
        migrations.AddField(
            model_name='dictionarycard',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_cards', to='trainer.mydictionary', verbose_name='Словарь'),
        ),
        migrations.AddIndex(
            model_name='dictionarycard',
            index=models.Index(fields=['dictionary', 'is_learned'], name='trainer_dic_diction_6ce2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='dictionarycard',
            index=models.Index(fields=['dictionary', 'added_at'], name='trainer_dic_diction_f278fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dictionarycard',
            unique_together={('dictionary', 'card')},
        ),
    ]
